### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by yatzyt** [Haochenlucas/GamingSupervisor#18]
![image](https://user-images.githubusercontent.com/8888867/36284587-66b18a42-1265-11e8-8605-ae7f8e17adab.png)

**Comment by yatzyt** [comment]
https://www.opendota.com/matches/3736096126
This was the replay if it helps.

**Comment by yatzyt** [comment]
>Rattletrap, the Clockwerk

Btw

**Comment by dominate0704** [comment]
solved
