### ISSUE TITLE
Controller Crashing

### ISSUE THREAD

**Issue by yatzyt** [Haochenlucas/GamingSupervisor#47]
> Managed Debugging Assistant 'FatalExecutionEngineError' : 'The runtime has encountered a fatal error. The address of the error was at 0x71510815, on thread 0x4610. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'

Remember the error I got with the controller? Got it again. I don't know how to replicate it though.

**Comment by theoculus8** [comment]
Probably an issue with Yato. Will not be fixed.
