### ISSUE TITLE
InvalidCastException: Direct2DRenderer.cs, Line 323, Fxn EndScene()

### ISSUE THREAD

**Issue by Haochenlucas** [Haochenlucas/GamingSupervisor#62]
System.InvalidCastException: 'Unable to cast object of type 'System.Object[]' to type 'SharpDX.ComObjectShadow'.'

System randomly crashes on InvalidCastException.

**Comment by theoculus8** [comment]
Doesn't appear when not using Visual Studio, will not be fixed.
